FROM node:12-buster-slim AS deps

WORKDIR /usr/app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile
# Build containter
FROM node:12-buster-slim AS builder

RUN npm install --global pm2
WORKDIR /usr/app
COPY . .

COPY --from=deps /usr/app/node_modules ./node_modules
RUN yarn build
#Expose na port 300
ENV PORT 3000
EXPOSE 3000
#Run cmd
CMD ["pm2-runtime", "npm", "--",  "start"]